title:            Anas AIT-ALI
description:      To do so...
logo:             anas_artwork.jpg
disqus_shortname: aitali
# Assign a default image for your site's header and footer
default_bg:       melbourne_bg.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
triangleheader:	  true
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://localhost:4000
# baseurl:

excerpt_separator: <!--more-->
# Gems used
gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

# Archives configuration
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

# Owner/author information
author:
  name:           Anas AIT-ALI
  picture:        anas.png
  email:          contact@aitali.co
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Some Details about yourself
  # Social networking links used in footer. Update and remove as you like.
  twitter: "anasaitali"
  facebook:
  github: "anas10"
  linkedin: "https://www.linkedin.com/in/anasaitali"
  instagram: "ceintureetbretelles/"
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "http://plus.google.com/123123123123132123"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-58530654-2
google_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags

# Sitemap configuration
# https://github.com/kinnetica/jekyll-plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
markdown:    kramdown
highlighter: rouge
paginate:    6
paginate_path: "/page:num/"

# https://github.com/mojombo/jekyll/wiki/Permalinks
collections:
  posts:
    output: true
    permalink: /article/:title
  pages:
    output: true
    permalink: /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
